### ISSUE TITLE
metadata from uri

### ISSUE THREAD

**Issue by annebaui** [smarnach/pyexiftool#1]
hi, is it possible to get the metadata of an uri like this:
metadata = et.get_tag("MWG:Description", "http://anne-bauermeister.de/srimatopics/gecko.jpg")

?
just getting ValueError: No JSON object could be decoded back

**Comment by smarnach** [comment]
PyExifTool is just a wrapper around the `exiftool` command-line utility.  Since `exiftool` only operates on local files, PyExifTool has the same limitation.

The easiest way around this is to download the file using `urllib2.urlopen()` and save it to a temporary file (`tempfile.NamedTemporaryFile()`),

**Comment by annebaui** [comment]
ok, thanks for answering that fast - i did it right the way you described it
