### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [smarnach/pyexiftool#32]
...

**Comment by BluelyTASer** [comment]
Even if you try it with executable set to windows executable, it will still doesn't work!!!
![710](https://user-images.githubusercontent.com/59511669/103111213-45961800-4629-11eb-9240-75af78bb7e9a.PNG)

**Comment by BluelyTASer** [comment]
The only way to get around it is to ignore pyexiftool and then use `print(os.popen("exiftool <file name>").read().splitlines())` which it prints the entire file's metadata or use my code from the screenshot which makes easier to capture each of file's metadata and it prints each of them's metadata information, since it's small lines of code, I wouldn't fork and pull request this pyexiftool.
![711](https://user-images.githubusercontent.com/59511669/103111247-cd7c2200-4629-11eb-92a5-25ff45a6a2a5.PNG)

**Comment by sylikc** [comment]
@BluelyTASer I can look into this... I would be able to fix it in my fork (https://github.com/sylikc/pyexiftool).  How do I get all of this environment running together?

So, I would install Pydroid, and then ... how do I reproduce the perl exiftool distribution?  The detection of exiftool running is sort of rudimentary in the current code... it certainly doesn't take the Perl version into account (I believe exiftool is compiled from Perl)
